-- PostgreSQL / Supabase version

CREATE TABLE "__MigrationLog" (
    "Name" VARCHAR(200) PRIMARY KEY,
    "ExecutedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Clinica" (
    "Id_Clinica" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" VARCHAR(150),
    "Direccion" VARCHAR(300),
    "Telefono" VARCHAR(50),
    "Mail" VARCHAR(320),
    "Rating" DECIMAL(3,2)
);

CREATE TABLE "Role" (
    "Id_Role" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE "User" (
    "Id_User" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" VARCHAR(100),
    "Apellido" VARCHAR(100),
    "Mail" VARCHAR(320) NOT NULL UNIQUE,
    "Contrasena" VARCHAR(255) NOT NULL,
    "Telefono" VARCHAR(30),
    "FechaRegistro" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "FotoPerfil" VARCHAR(500),
    "Ubicacion" VARCHAR(300),
    "Estado" BOOLEAN DEFAULT TRUE
);

CREATE TABLE "Mascota" (
    "Id_Mascota" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Id_User" INTEGER NOT NULL REFERENCES "User"("Id_User"),
    "Nombre" VARCHAR(100),
    "Especie" VARCHAR(50),
    "Raza" VARCHAR(100),
    "FechaNacimiento" DATE,
    "Peso" DECIMAL(5,2),
    "Foto" VARCHAR(500),
    "EstadoSalud" VARCHAR(200),
    "ChipId" VARCHAR(100)
);

CREATE TABLE "Vacuna" (
    "Id_Vacuna" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" VARCHAR(150),
    "Dosis" VARCHAR(100)
);

CREATE TABLE "MascotaVacuna" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Id_Mascota" INTEGER NOT NULL REFERENCES "Mascota"("Id_Mascota"),
    "Id_Vacuna" INTEGER NOT NULL REFERENCES "Vacuna"("Id_Vacuna"),
    "FechaAplicacion" DATE,
    "ProximaDosis" DATE,
    "AplicadaPor" VARCHAR(150)
);

CREATE TABLE "Publicacion" (
    "Id_Publicacion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Id_User" INTEGER NOT NULL REFERENCES "User"("Id_User"),
    "Id_Mascota" INTEGER REFERENCES "Mascota"("Id_Mascota"),
    "ImagenUrl" VARCHAR(500),
    "Descripcion" VARCHAR(2000),
    "Fecha" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Comentario" (
    "Id_Comentario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Id_Publicacion" INTEGER NOT NULL REFERENCES "Publicacion"("Id_Publicacion"),
    "Id_User" INTEGER NOT NULL REFERENCES "User"("Id_User"),
    "Contenido" VARCHAR(1000),
    "Fecha" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "HistorialEvento" (
    "Id_Evento" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Id_Mascota" INTEGER NOT NULL REFERENCES "Mascota"("Id_Mascota"),
    "Tipo" VARCHAR(50),
    "Fecha" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "Descripcion" VARCHAR(1000),
    "Visibilidad" BOOLEAN DEFAULT TRUE
);

CREATE TABLE "Tratamiento" (
    "Id_Tratamiento" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Id_Mascota" INTEGER NOT NULL REFERENCES "Mascota"("Id_Mascota"),
    "Nombre" VARCHAR(150),
    "Veterinario" VARCHAR(150),
    "FechaInicio" DATE,
    "FechaFin" DATE,
    "Observaciones" VARCHAR(1000)
);

CREATE TABLE "Veterinario" (
    "Id_Vet" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Id_Clinica" INTEGER REFERENCES "Clinica"("Id_Clinica"),
    "Nombre" VARCHAR(150),
    "Matricula" VARCHAR(100),
    "Especialidad" VARCHAR(150)
);

CREATE TABLE "Notificacion" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Id_User" INTEGER NOT NULL REFERENCES "User"("Id_User"),
    "Titulo" VARCHAR(150),
    "Mensaje" VARCHAR(500),
    "Tipo" VARCHAR(50),
    "Leido" BOOLEAN DEFAULT FALSE,
    "Fecha" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Paseo" (
    "Id_Paseo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Id_Mascota" INTEGER NOT NULL REFERENCES "Mascota"("Id_Mascota"),
    "Id_Walker" INTEGER REFERENCES "User"("Id_User"),
    "HoraInicio" TIMESTAMP,
    "HoraFin" TIMESTAMP,
    "UbicacionInicio" VARCHAR(300),
    "UbicacionFin" VARCHAR(300),
    "Estado" VARCHAR(50),
    "Rating" INTEGER
);

CREATE TABLE "PaseoTrack" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Id_Paseo" INTEGER NOT NULL REFERENCES "Paseo"("Id_Paseo"),
    "Lat" DECIMAL(10,7),
    "Lng" DECIMAL(10,7),
    "Timestamp" TIMESTAMP
);

CREATE TABLE "Match" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "idMascotaUno" INTEGER NOT NULL REFERENCES "Mascota"("Id_Mascota"),
    "idMascotaDos" INTEGER NOT NULL REFERENCES "Mascota"("Id_Mascota"),
    "idUsuarioUno" INTEGER NOT NULL REFERENCES "User"("Id_User"),
    "idUsuarioDos" INTEGER NOT NULL REFERENCES "User"("Id_User"),
    "fecha" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "activo" BOOLEAN DEFAULT TRUE,
    UNIQUE ("idMascotaUno","idMascotaDos")
);

CREATE TABLE "Mensaje" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "idMatch" INTEGER NOT NULL REFERENCES "Match"("id"),
    "idUsuario" INTEGER NOT NULL REFERENCES "User"("Id_User"),
    "texto" VARCHAR(2000),
    "fecha" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "leido" BOOLEAN DEFAULT FALSE
);

CREATE TABLE "Voto" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "idMascotaOrigen" INTEGER NOT NULL REFERENCES "Mascota"("Id_Mascota"),
    "idMascotaDestino" INTEGER NOT NULL REFERENCES "Mascota"("Id_Mascota"),
    "leGusta" BOOLEAN NOT NULL,
    "fecha" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE ("idMascotaOrigen","idMascotaDestino")
);

CREATE TABLE "UserRole" (
    "Id_User" INTEGER NOT NULL REFERENCES "User"("Id_User"),
    "Id_Role" INTEGER NOT NULL REFERENCES "Role"("Id_Role"),
    PRIMARY KEY ("Id_User","Id_Role")
);

INSERT INTO "Role" ("Id_Role","Nombre") VALUES
(1,'OWNER'),
(2,'WALKER'),
(3,'VET'),
(4,'CLINIC'),
(5,'ADMIN');

CREATE INDEX "IX_Match_MascotaUno" ON "Match"("idMascotaUno");
CREATE INDEX "IX_Match_MascotaDos" ON "Match"("idMascotaDos");
CREATE INDEX "IX_Mensaje_Match" ON "Mensaje"("idMatch","fecha");
CREATE INDEX "IX_Voto_Destino" ON "Voto"("idMascotaDestino");
